#
# Since: April 2025
# Author: gvenzl
# Name: build.yaml
# Description: Build script
#
# Copyright 2025 Gerald Venzl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Build sysmonitor
on: [push, pull_request]
jobs:
  build-mac-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        run: |
          brew install openjdk@21
          sudo ln -sfn /opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-21.jdk

      - name: Build
        run: mvn install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Mac OSX arm64"
          path: target/installer/SysMonitor-1.0.0.dmg
  
  build-mac-intel:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        run: |
          brew install openjdk@21
          sudo ln -sfn /usr/local/opt/openjdk@21/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-21.jdk

      - name: Build
        run: |
          export PATH=/usr/local/opt/openjdk@21/bin:$PATH
          export JAVA_HOME=/usr/local/opt/openjdk@21
          mvn install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Mac OSX x86"
          path: target/installer/SysMonitor-1.0.0.dmg

  build-linux-intel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        run: sudo update-java-alternatives -s temurin-21-jdk-amd64

      - name: Build
        run: |
          export JAVA_HOME=/usr/lib/jvm/temurin-21-jdk-amd64
          mvn install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Linux rpm x86"
          path: target/installer/sysmonitor-1.0.0-1.x86_64.rpm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Linux deb x86"
          path: target/installer/sysmonitor_1.0.0_amd64.deb

  build-windows-intel:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        run: winget install --accept-package-agreements --accept-source-agreements --exact --id Microsoft.OpenJDK.21

      - name: Build
        run: |
          $env:JAVA_HOME="C:\Program Files\Microsoft\jdk-21.0.7.6-hotspot"
          $env:Path="$env:JAVA_HOME\bin;$env:Path"
          mvn install
          dir target/installer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Windows x86"
          path: target/installer/SysMonitor-1.0.0.msi
